spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/grooming
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/grooming
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: 2GiJ6jfi8NNGC6v5XeIxFFbXfBnUJYgw
            scope: openid
  datasource:
    url: jdbc:mysql://localhost:3306/new_schema11
    username: root
    password: 123456
server:
  port: 3000
  logging:
    level:
      org.springframework.security: TRACE
